### PR TITLE
Fix Travis CI failing on AWSException unit test

### LINKED ISSUE #84: CI Failing - Unable to reference AWSException
Problem
---
> https://travis-ci.org/JuliaCloud/AWSCore.jl/builds/580418604

The current `master` branch is failing on Travis CI for the following line:

> https://github.com/JuliaCloud/AWSCore.jl/blob/master/test/runtests.jl#L569

With the exception:

```
Exception: Error During Test at /Users/mattbr/.julia/dev/AWSCore.jl/test/runtests.jl:557
  Got exception outside of a @test
  UndefRefError: access to undefined reference
```

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Notes
---
- Resolves #84 
- [AWSCore.jl Travis CI Failures](https://travis-ci.org/JuliaCloud/AWSCore.jl/builds/580418604)

Problem
---
The `access to undefined reference` is inside of `HTTP.StatusError()`
```
ex = AWSException(HTTP.StatusError(status_code, resp))
```

> https://github.com/JuliaWeb/HTTP.jl/blob/master/src/ExceptionRequest.jl#L45
```
StatusError(status, response::HTTP.Response) = StatusError(status, response.request.method, response.request.target, response)
```

We are defining our `HTTP.Response` as:
```
    code = "InvalidSignatureException"
    message = "Signature expired: ..."
    body = """
        {
           "__type": "$code",
           "message": "$message"
        }
        """
    resp = HTTP.Messages.Response(400, body)
```

When calling the `StatusError()`, we have not defined `resp.request.method` or `resp.request.target` which leads to this error.

Solution
---
To resolve this we need to create a `HTTP.Request` object and include it in the `HTTP.Response` object. In this unit test I just used the same `headers` and `body` for both the `HTTP.Request`/`HTTP.Response` objects as it's just test data.

```
req = HTTP.Request("GET", "http://therainforest.com", headers, body)
resp = HTTP.Response(status_code, headers; body=body, request=req)
ex = AWSException(HTTP.StatusError(status_code, resp))
```

### CODE REVIEW

**Comment by rofinn** [comment]
bors +r

**Comment by ararslan** [comment]
My bad I forgot how to do the thing.

bors try

**Comment by mattBrzezinski** [comment]
Force-pushed an amended commit with a version number bump from `0.6.1` -> `0.6.2`

File: test/runtests.jl [hunk 1]
```diff
@@ -563,10 +561,12 @@ end
            "message": "$message"
         }
         """
-    resp = HTTP.Messages.Response(400, body)
-    HTTP.setheader(resp.headers, "Content-Type" => "application/x-amz-json-1.1")
+    headers = ["Content-Type" => "application/x-amz-json-1.1"]
+    status_code = 400
 
-    ex = AWSException(HTTP.StatusError(400, resp))
+    req = HTTP.Request("GET", "http://therainforest.com", headers, body)
```
Comment (omus) [inline test/runtests.jl]: Maybe add a comment that this won't actually connect to this server? Maybe consider using http://httpbin.org/ for testing

Comment (mattBrzezinski) [reply test/runtests.jl]: Good idea. I'll write a comment explaining that this doesn't actually message the server.

I'm also updating this to properly be `https://amazon.ca`, as this test is for `AWSException()`, I feel like it should hit the appropriate website to be clear.

**Comment by mattBrzezinski** [comment]
bors try
